import { useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import rehypeSanitize from "rehype-sanitize";
import { PageHero } from "@/components/PageHero";
import { EmptyState } from "@/components/EmptyState";
import { ContactForm } from "@/components/ContactForm";
import { profile } from "@/data/profile";
import { contact } from "@/data/contact";
import { skills, skillCategories } from "@/data/skills";
import { experience } from "@/data/experience";
import { education } from "@/data/education";
import { certifications } from "@/data/certifications";
import { achievements } from "@/data/achievements";
import { services } from "@/data/services";
import { projects, projectCategories } from "@/data/projects";
import { research } from "@/data/research";
import { siteSettings } from "@/data/siteSettings";
import { blogPosts } from "@/utils/blog";
import { matchesSearch, published, readingTime } from "@/utils/content";

const Card=({title,subtitle,body}:{title:string;subtitle?:string;body:string})=><article className="card p-6">{subtitle&&<p className="eyebrow">{subtitle}</p>}<h2 className="mt-2 text-xl font-semibold">{title}</h2><p className="mt-3 text-sm leading-6 text-muted">{body}</p></article>;
export function About(){return <><PageHero eyebrow="Professional profile" title="About me" description="Background, values, professional direction, and current focus."/><section className="container-shell grid gap-5 py-14 md:grid-cols-2"><Card title="Professional summary" body={profile.summary}/><Card title="Career objective" body={profile.careerObjective}/><Card title="Current focus" body={profile.currentFocus}/><Card title="Professional values" body={profile.values.join(" · ")}/></section></>}
export function Skills(){const [q,setQ]=useState(""),[cat,setCat]=useState("All");const items=published(skills).filter(x=>(cat==="All"||x.category===cat)&&matchesSearch([x.name,x.description,x.category],q));return <><PageHero eyebrow="Capabilities" title="Skills & tools" description="A transparent, evidence-based view of technologies and professional practices."/><Filter q={q} setQ={setQ} value={cat} setValue={setCat} options={["All",...skillCategories]}/><section className="container-shell grid gap-5 pb-14 md:grid-cols-2 lg:grid-cols-3">{items.length?items.map(x=><Card key={x.id} title={x.name} subtitle={`${x.category} · ${x.level}`} body={x.description}/>):<EmptyState label="skills"/>}</section></>}
export function Experience(){const items=published(experience);return <Listing eyebrow="Career journey" title="Experience" description="Formal roles and independent work are clearly distinguished." items={items.map(x=>({id:x.id,title:x.title,subtitle:x.workType,body:`${x.organisation}. ${x.overview}`}))} empty="experience"/>}
export function Education(){const items=published(education);return <Listing eyebrow="Academic foundation" title="Education" description="Qualifications and research details, with no invented results or dates." items={items.map(x=>({id:x.id,title:x.qualification,subtitle:x.institution,body:[x.field,x.completionYear,x.description].filter(Boolean).join(" · ")}))} empty="education entries"/>}
export function Certifications(){const [q,setQ]=useState(""),[cat,setCat]=useState("All");const all=published(certifications);const categories=["All",...new Set(all.map(x=>x.category))];const items=all.filter(x=>(cat==="All"||x.category===cat)&&matchesSearch([x.title,x.organisation,...x.skills],q));return <><PageHero eyebrow="Continuous learning" title="Certifications & training" description="Only genuine, verifiable credentials are published."/><Filter q={q} setQ={setQ} value={cat} setValue={setCat} options={categories}/><section className="container-shell grid gap-5 pb-14 md:grid-cols-2 lg:grid-cols-3">{items.length?items.map(x=><Card key={x.id} title={x.title} subtitle={x.organisation} body={x.description}/>):<EmptyState label="certifications"/>}</section></>}
export function Achievements(){const items=published(achievements);return <Listing eyebrow="Milestones" title="Achievements" description="Awards, research milestones, disclosures, and recognition appear only with genuine evidence." items={items.map(x=>({id:x.id,title:x.title,subtitle:x.category,body:x.description}))} empty="achievements"/>}
export function Services(){const items=siteSettings.servicesEnabled?published(services):[];return <><PageHero eyebrow="Professional support" title="Services" description="Optional services within a clear ethical and legal scope."/><section className="container-shell py-14"><p className="mb-8 rounded-xl border border-brand/30 bg-brand/5 p-4 text-sm"><strong>Ethical notice:</strong> All security testing services are performed only with explicit written authorisation.</p><div className="grid gap-5 md:grid-cols-3">{items.length?items.map(x=><Card key={x.id} title={x.title} body={`${x.description} ${x.points.join(" · ")}`}/>):<EmptyState label="services"/>}</div></section></>}
export function Laboratory(){return <><PageHero eyebrow="Technical environment" title="MikroTik networking home lab" description="A controlled space for building practical networking, systems, and security skills."/><section className="container-shell grid gap-5 py-14 md:grid-cols-2"><Card title="RouterOS practice" body="Hands-on learning with MikroTik RouterOS configuration, interface setup, IP addressing, DHCP, NAT, routing concepts, and firewall rules."/><Card title="Troubleshooting mindset" body="Testing connectivity, identifying configuration issues, and documenting changes in a safe lab environment."/><Card title="Systems learning" body="Using Windows, Linux, and virtualised environments to strengthen IT support and administration fundamentals."/><Card title="Security awareness" body="Applying security-first thinking to segmentation, firewall configuration, access control, and responsible lab practice."/></section></>}
export function Projects(){const [q,setQ]=useState(""),[cat,setCat]=useState("All");const items=published(projects).filter(x=>(cat==="All"||x.category===cat)&&matchesSearch([x.title,x.summary,...x.tags,...x.technologies],q));return <><PageHero eyebrow="Selected work" title="Projects & case studies" description="Searchable work with exact roles, security considerations, evidence, and outcomes."/><Filter q={q} setQ={setQ} value={cat} setValue={setCat} options={["All",...projectCategories]}/><section className="container-shell grid gap-5 pb-14 md:grid-cols-2 lg:grid-cols-3">{items.length?items.map(x=><Link to={`/projects/${x.slug}`} key={x.id}><Card title={x.title} subtitle={x.category} body={x.summary}/></Link>):<EmptyState label="projects"/>}</section></>}
export function ProjectDetail(){const {slug}=useParams();const item=published(projects).find(x=>x.slug===slug);if(!item)return <NotFound/>;return <article className="container-shell max-w-4xl py-18"><Link to="/projects" className="text-brand">← Projects</Link><p className="eyebrow mt-12">{item.category}</p><h1 className="mt-4 text-4xl font-semibold sm:text-6xl">{item.title}</h1><p className="mt-6 text-xl leading-8 text-muted">{item.summary}</p><div className="prose-custom mt-12"><ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeSanitize]}>{item.description}</ReactMarkdown></div>{item.githubUrl&&<a href={item.githubUrl} target="_blank" rel="noopener noreferrer" className="mt-8 inline-block text-brand">GitHub repository →</a>}</article>}
export function Research(){return <><PageHero eyebrow="Dedicated research case study" title={research.title} description={research.overview}/><section className="container-shell grid gap-8 py-14 lg:grid-cols-[1fr_20rem]"><article className="card p-8 prose-custom"><h2>Research overview</h2><p>{research.background}</p><h2>Problem and gap</h2><p>{research.problem} {research.researchGap}</p><h2>Methodology and architecture</h2><p>{research.methodology} {research.architecture}</p><h2>Main results</h2><p>{research.results.length?research.results.join(" "):"Verified evaluation results have not been published yet."}</p></article><aside><p className="eyebrow">Security modules</p><div className="mt-4 grid gap-2">{research.modules.map((x,i)=><div className="rounded-xl border bg-surface p-3 text-sm" key={x}><span className="mr-2 font-mono text-xs text-brand">{String(i+1).padStart(2,"0")}</span>{x}</div>)}</div></aside></section></>}
export function Blog(){const [q,setQ]=useState(""),[cat,setCat]=useState("All");const categories=["All",...new Set(blogPosts.map(x=>x.category))];const items=blogPosts.filter(x=>(cat==="All"||x.category===cat)&&matchesSearch([x.title,x.excerpt,...x.tags],q));return <><PageHero eyebrow="Knowledge base" title="Notes from practice & research" description="Published Markdown articles about IT, security, development, and research."/><Filter q={q} setQ={setQ} value={cat} setValue={setCat} options={categories}/><section className="container-shell grid gap-5 pb-14 md:grid-cols-2">{items.length?items.map(x=><Link key={x.slug} to={`/blog/${x.slug}`}><Card title={x.title} subtitle={`${x.category} · ${readingTime(x.content)} min`} body={x.excerpt}/></Link>):<EmptyState label="blog posts"/>}</section></>}
export function BlogPost(){const {slug}=useParams();const item=blogPosts.find(x=>x.slug===slug);if(!item)return <NotFound/>;return <article className="container-shell max-w-4xl py-18"><Link to="/blog" className="text-brand">← Blog</Link><p className="eyebrow mt-12">{item.category}</p><h1 className="mt-4 text-4xl font-semibold sm:text-6xl">{item.title}</h1><p className="mt-5 text-muted">{item.date} · {readingTime(item.content)} min read</p><div className="prose-custom mt-10"><ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeSanitize]}>{item.content}</ReactMarkdown></div></article>}
export function Contact(){const links=[contact.email&&`Email: ${contact.email}`,contact.githubUrl&&"GitHub",contact.linkedinUrl&&"LinkedIn",contact.whatsappNumber&&"WhatsApp"].filter(Boolean);return <><PageHero eyebrow="Start a conversation" title="Contact" description="Share context about an opportunity, research question, or technical requirement."/><section className="container-shell grid gap-8 py-14 lg:grid-cols-[.65fr_1.35fr]"><aside className="card h-fit p-6"><h2 className="font-semibold">Direct contact</h2><p className="mt-3 text-sm leading-6 text-muted">{contact.responseTime}</p><div className="mt-5 grid gap-2 text-sm">{links.length?links.map(x=><span key={String(x)}>{x}</span>):<span className="text-muted">Add public contact methods in src/data/contact.ts.</span>}</div></aside><ContactForm/></section></>}
export function Resume(){return <article className="container-shell max-w-5xl py-12"><div className="no-print mb-8 rounded-xl border bg-surface p-4 text-sm text-muted">Add <code>public/documents/cv.pdf</code> to enable a verified PDF download. Use the browser print command for an A4 copy.</div><h1 className="text-4xl font-semibold">{profile.fullName}</h1><p className="mt-2 text-brand">{profile.professionalTitle}</p><section className="mt-8"><h2 className="text-xl font-semibold">Professional summary</h2><p className="mt-3 leading-7 text-muted">{profile.summary}</p></section><section className="mt-8"><h2 className="text-xl font-semibold">Education</h2>{published(education).map(x=><div className="mt-4 card p-5" key={x.id}><h3 className="font-semibold">{x.qualification} · {x.institution}</h3><p className="mt-2 text-sm text-muted">{x.description}</p></div>)}</section></article>}
export function Search(){const [q,setQ]=useState("");const results=useMemo(()=>{if(q.trim().length<2)return[];return [...published(projects).map(x=>({title:x.title,body:x.summary,path:`/projects/${x.slug}`})),...published(skills).map(x=>({title:x.name,body:x.description,path:"/skills"})),...blogPosts.map(x=>({title:x.title,body:x.excerpt,path:`/blog/${x.slug}`}))].filter(x=>matchesSearch([x.title,x.body],q)).slice(0,20)},[q]);return <><PageHero eyebrow="Site search" title="Find portfolio content" description="Search published projects, skills, and articles."/><section className="container-shell max-w-4xl py-14"><input className="h-12 w-full rounded-xl border bg-surface px-4" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search…"/><div className="mt-6 grid gap-3">{results.map(x=><Link className="card p-5" key={`${x.path}-${x.title}`} to={x.path}><h2 className="font-semibold">{x.title}</h2><p className="mt-2 text-sm text-muted">{x.body}</p></Link>)}</div></section></>}
export function Disclosure(){return <Policy title="Responsible disclosure"><h2>Authorisation</h2><p>Unauthorised testing is not permitted. Denial-of-service testing, social engineering, destructive testing, and privacy violations are prohibited.</p><h2>Reporting</h2><p>Use the contact page and include the affected URL, concise reproduction steps, potential impact, and safe evidence. Do not include personal data. Scope and response expectations must be completed by the site owner.</p></Policy>}
export function Accessibility(){return <Policy title="Accessibility statement"><p>This site supports semantic structure, keyboard navigation, a skip link, visible focus, reduced motion, responsive layouts, accessible forms, and print-friendly resume output.</p><p>Please report barriers through the contact page with your browser, device, and assistive technology.</p></Policy>}
export function NotFound(){return <main className="container-shell py-32 text-center"><p className="eyebrow">404</p><h1 className="mt-4 text-4xl font-semibold">Page not found</h1><Link className="mt-6 inline-block text-brand" to="/">Return home →</Link></main>}
function Policy({title,children}:{title:string;children:React.ReactNode}){return <><PageHero eyebrow="Policy" title={title} description="Professional, responsible, and transparent website use."/><article className="container-shell max-w-4xl py-14 prose-custom">{children}</article></>}
function Listing({eyebrow,title,description,items,empty}:{eyebrow:string;title:string;description:string;items:{id:string;title:string;subtitle:string;body:string}[];empty:string}){return <><PageHero eyebrow={eyebrow} title={title} description={description}/><section className="container-shell grid gap-5 py-14 md:grid-cols-2 lg:grid-cols-3">{items.length?items.map(x=><Card key={x.id} title={x.title} subtitle={x.subtitle} body={x.body}/>):<EmptyState label={empty}/>}</section></>}
function Filter({q,setQ,value,setValue,options}:{q:string;setQ:(x:string)=>void;value:string;setValue:(x:string)=>void;options:string[]}){return <div className="container-shell flex flex-col gap-3 py-8 sm:flex-row"><input value={q} onChange={e=>setQ(e.target.value)} className="h-11 flex-1 rounded-xl border bg-surface px-4" placeholder="Search…"/><select value={value} onChange={e=>setValue(e.target.value)} className="h-11 rounded-xl border bg-surface px-4">{options.map(x=><option key={x}>{x}</option>)}</select></div>}
